apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: llama-raycluster-ephemeral # Changed name slightly to reflect ephemeral nature
spec:
  rayVersion: '2.46.0'
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
      num-cpus: '0'
    template:
      spec:
        containers:
          - name: ray-head
            image: rayproject/ray-ml:2.46.0.0e19ea-py310
            ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
            resources:
              limits:
                cpu: "2"
                memory: "8Gi"
              requests:
                cpu: "1"
                memory: "4Gi"
            env:
              - name: HF_HOME
                value: "/mnt/hf_cache"
              - name: TF_CPP_MIN_LOG_LEVEL
                value: "2"
            volumeMounts:
            - name: hf-token-volume
              mountPath: "/etc/hf-token"
              readOnly: true
            - name: hf-cache-storage
              mountPath: "/mnt/hf_cache"
            - name: output-storage
              mountPath: "/mnt/pvc"
        volumes:
          - name: hf-token-volume
            secret:
              secretName: hf-secret
          - name: hf-cache-storage
            emptyDir: {}
          - name: output-storage
            emptyDir: {}
  workerGroupSpecs:
  - replicas: 8
    groupName: gpu-workers
    rayStartParams: {}
    template:
      spec:
        nodeSelector:
          cloud.google.com/gke-accelerator: nvidia-h100-mega-80gb
        tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        containers:
        - name: ray-worker
          image: rayproject/ray-ml:2.46.0.0e19ea-py310
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "20"
              memory: "50Gi"
              nvidia.com/gpu: "1"
            requests:
              cpu: "16"
              memory: "40Gi"
              nvidia.com/gpu: "1"
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
            - name: HF_HOME
              value: "/mnt/hf_cache"
            - name: TF_CPP_MIN_LOG_LEVEL
              value: "2"
          volumeMounts:
          - name: hf-token-volume
            mountPath: "/etc/hf-token"
            readOnly: true
          - name: hf-cache-storage
            mountPath: "/mnt/hf_cache"
          - name: output-storage
            mountPath: "/mnt/pvc"
        volumes:
          - name: hf-token-volume
            secret:
              secretName: hf-secret
          - name: hf-cache-storage
            emptyDir: {}
          - name: output-storage
            emptyDir: {}